name: Api Mongoose V1 Heroku

#On: es cuando se va a ejecutar este workflow
on:
  push:
    branches:
      - master

jobs:
#Stages -> Los procesos (pasos) de CI que tiene que hacer este Workflow
#Este workflow tiene que hacer 2 cosas:
# 1) Compilar (hacer el build)
# 2) Testear (ejecutar las pruebas)
  build:
    #Aqui indico al CI el Sistema Operativo en que se va a ejecutar.
    runs-on: ubuntu-latest

    #Steps: Indicamos los pasos para hacer que build funcione
    steps:
      - uses: actions/checkout@v2
      - name: Login al Heroku Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build & Push de mi imagen
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker build . --tag api-mongoose-v1 -f docker/prod/Dockerfile
          docker tag api-mongoose-v1 registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web

    # esto de abajo es antes de cambios a producción en heroku
    #- uses: actions/checkout@v2
      #uses: Que versión de actions va a ocupar
    #name: Nombra el paso en que estas
    #- name: Build image Docker
    #run: ejecuta un comando especifico (en este caso de linux)
    #  run: docker build . --file Dockerfile --tag api-mongoose-v1

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test API
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Configuro el entorno que necesita node para funcionar
      #npm ci lo que hace es instalar desde el package-lock.json, por lo que instala la versión exacta y es más rápido
      - run: npm ci
      - run: npm test
        env:
          MONGO_URI: mongodb://db:27017/apimongo
          FB_PROJECT_ID: ''
          FB_KEYFILENAME: ''
          FB_BUCKET_URL: ''